name: boxing_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.3=he30d5cf_0
  - aom=3.6.1=h0425590_0
  - arm-variant=1.2.0=sbsa
  - attr=2.5.1=h4e544f5_1
  - backports.zstd=1.3.0=py310hfa1aa29_0
  - blas=1.0=openblas
  - brotli=1.2.0=hd651790_1
  - brotli-bin=1.2.0=he30d5cf_1
  - brotli-python=1.2.0=py310hbe54bbb_1
  - bzip2=1.0.8=h4777abc_8
  - c-ares=1.34.6=he30d5cf_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h83712da_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - chumpy=0.70=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hf54e67a_0
  - cuda-cudart=12.9.79=h3ae8b8a_0
  - cuda-cudart_linux-aarch64=12.9.79=h3ae8b8a_0
  - cuda-nvrtc=12.9.86=h8f3c8d4_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=8.9.7.29=h00485f9_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=h6c5dea3_0
  - cython=3.2.4=py310h0d97cfb_0
  - dav1d=1.2.1=h31becfc_0
  - dbus=1.16.2=h70963c4_1
  - double-conversion=3.3.1=h5ad3122_0
  - ffmpeg=6.0.1=gpl_h76c8505_100
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h8dda3cd_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310h2d8da20_0
  - freeglut=3.2.2=h5eeb66e_3
  - freetype=2.14.1=h8af1aa0_0
  - fribidi=1.0.16=he30d5cf_0
  - glib=2.86.3=haf01fca_0
  - glib-tools=2.86.3=hbdb84e1_0
  - gmp=6.3.0=h0a1ffab_2
  - gnutls=3.7.9=hb309da9_0
  - graphite2=1.3.14=hfae3067_2
  - gst-plugins-base=1.24.11=h83ffb7f_0
  - gstreamer=1.24.11=h17c303d_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=he4899c9_0
  - hdf5=1.14.3=nompi_h6ed7ac7_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hf9b3779_0
  - idna=3.11=pyhd8ed1ab_0
  - jasper=4.2.8=h27a9ab5_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - keyutils=1.6.3=h86ecc28_0
  - kiwisolver=1.4.9=py310h65c7496_2
  - krb5=1.21.3=h50a48e9_0
  - lame=3.100=h4e544f5_1003
  - lcms2=2.18=h9d5b58d_0
  - ld_impl_linux-aarch64=2.45=default_h1979696_105
  - lerc=4.0.0=hfdc4d58_1
  - libabseil=20230802.1=cxx17_h2f0025b_0
  - libaec=1.1.5=hff7e48a_0
  - libass=0.17.1=hcc173ff_2
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.2.0=he30d5cf_1
  - libbrotlidec=1.2.0=he30d5cf_1
  - libbrotlienc=1.2.0=he30d5cf_1
  - libcap=2.77=h68e9139_0
  - libcblas=3.9.0=13_h8345d7a_netlib
  - libclang-cpp20.1=20.1.8=default_he95a3c9_8
  - libclang-cpp21.1=21.1.8=default_he95a3c9_2
  - libclang13=21.1.8=default_h94a09a5_2
  - libcublas=12.9.1.4=he38c790_1
  - libcups=2.3.3=h5cdc715_5
  - libcurl=8.18.0=h7bfdcfb_0
  - libdeflate=1.25=h1af38f5_0
  - libdrm=2.4.125=he30d5cf_1
  - libedit=3.1.20250104=pl5321h976ea20_0
  - libegl=1.7.0=hd24410f_2
  - libev=4.33=h31becfc_2
  - libevent=2.1.12=h4ba1bb4_1
  - libexpat=2.7.3=hfae3067_0
  - libffi=3.4.6=he21f813_1
  - libflac=1.5.0=he9c94f4_1
  - libfreetype=2.14.1=h8af1aa0_0
  - libfreetype6=2.14.1=hdae7a39_0
  - libgcc=15.2.0=h8acb6b2_16
  - libgcc-ng=15.2.0=he9431aa_16
  - libgfortran=15.2.0=h51576c1_7
  - libgfortran-ng=15.2.0=h51576c1_7
  - libgfortran5=15.2.0=hdc851ad_7
  - libgl=1.7.0=hd24410f_2
  - libglib=2.86.3=haa79c35_0
  - libglu=9.0.3=h5ad3122_1
  - libglvnd=1.7.0=hd24410f_2
  - libglx=1.7.0=hd24410f_2
  - libgomp=15.2.0=h8acb6b2_16
  - libhwloc=2.12.1=default_h6f258fa_1000
  - libiconv=1.18=h90929bb_2
  - libidn2=2.3.8=h99ff5a0_1
  - libjpeg-turbo=3.1.2=he30d5cf_0
  - liblapack=3.9.0=13_hfc05e43_netlib
  - liblapacke=3.9.0=13_h40010ee_netlib
  - libllvm20=20.1.8=h2b567e5_0
  - libllvm21=21.1.8=h42b457e_0
  - liblzma=5.8.2=he30d5cf_0
  - libnghttp2=1.67.0=ha888d0e_0
  - libnsl=2.0.1=h86ecc28_1
  - libntlm=1.4=hf897c2e_1002
  - libogg=1.3.5=h86ecc28_1
  - libopenblas=0.3.30=pthreads_h9d3fd7e_4
  - libopencv=4.8.1=py310h4a2c686_5
  - libopengl=1.7.0=hd24410f_2
  - libopenvino=2023.1.0=h2f0025b_2
  - libopenvino-arm-cpu-plugin=2023.1.0=h2f0025b_2
  - libopenvino-auto-batch-plugin=2023.1.0=h2f0025b_2
  - libopenvino-auto-plugin=2023.1.0=h2f0025b_2
  - libopenvino-hetero-plugin=2023.1.0=h2f0025b_2
  - libopenvino-ir-frontend=2023.1.0=h2f0025b_2
  - libopenvino-onnx-frontend=2023.1.0=h2f0025b_2
  - libopenvino-paddle-frontend=2023.1.0=h2f0025b_2
  - libopenvino-pytorch-frontend=2023.1.0=h2f0025b_2
  - libopenvino-tensorflow-frontend=2023.1.0=h2f0025b_2
  - libopenvino-tensorflow-lite-frontend=2023.1.0=h2f0025b_2
  - libopus=1.6.1=h80f16a2_0
  - libpciaccess=0.18=h86ecc28_0
  - libpng=1.6.54=h1abf092_0
  - libpq=17.7=haf03d9f_1
  - libprotobuf=4.24.4=h87e877f_0
  - librealsense=2.56.5=cuda129_py310_h4fd8441_202
  - libsndfile=1.2.2=h30591a0_2
  - libsqlite=3.51.2=h022381a_0
  - libssh2=1.11.1=h18c354c_0
  - libstdcxx=15.2.0=hef695bb_16
  - libstdcxx-ng=15.2.0=hdbbeba8_16
  - libsystemd0=258.3=h8c5a66d_0
  - libtasn1=4.21.0=he30d5cf_0
  - libtiff=4.7.1=hdb009f0_1
  - libudev1=258.3=h8c5a66d_0
  - libunistring=0.9.10=hf897c2e_0
  - libusb=1.0.29=h06eaf92_0
  - libuuid=2.41.3=h1022ec0_0
  - libvorbis=1.3.7=h7ac5ae9_2
  - libvpx=1.13.1=h2f0025b_0
  - libvulkan-loader=1.4.328.1=h8b8848b_0
  - libwebp-base=1.6.0=ha2e29f5_0
  - libxcb=1.17.0=h262b8f6_0
  - libxcrypt=4.4.36=h31becfc_1
  - libxkbcommon=1.11.0=h95ca766_0
  - libxml2=2.13.9=he58860d_0
  - libxslt=1.1.43=h4552c8e_0
  - libzlib=1.3.1=h86ecc28_2
  - matplotlib=3.10.8=py310hbbe02a8_0
  - matplotlib-base=3.10.8=py310hc06f52e_0
  - mpg123=1.32.9=h65af167_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=ha32ae93_3
  - nettle=3.9.1=h9d1147b_0
  - nspr=4.38=h3ad9384_0
  - nss=3.118=h544fa81_0
  - numpy-base=1.26.4=py310h9e825c3_1
  - opencv=4.8.1=py310h2ec3a81_5
  - openh264=2.3.1=hd600fc2_2
  - openjpeg=2.5.4=h5da879a_0
  - openldap=2.6.10=h30c48ee_0
  - openssl=3.6.1=h546c87b_1
  - p11-kit=0.24.1=h9f2702f_0
  - pcre2=10.46=h15761aa_0
  - pillow=12.1.0=py310hd8fe58f_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h7ac5ae9_1
  - ply=3.11=pyhd8ed1ab_3
  - pthread-stubs=0.4=h86ecc28_1002
  - pugixml=1.14=h2f0025b_0
  - pulseaudio-client=17.0=hcf98165_3
  - py-opencv=4.8.1=py310h3634b9b_5
  - pybind11-abi=11=hc364b38_1
  - pycocotools=2.0.11=py310h3fe14e7_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyqt=5.15.11=py310h5ffa702_2
  - pyqt5-sip=12.17.0=py310h57cea71_2
  - pyrealsense2=2.56.5=cuda129_py310_haef91de_202
  - pyside6=6.9.2=py310hd557e7c_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h28be5d3_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyyaml=6.0.3=py310h2d8da20_0
  - qhull=2020.2=h70be974_5
  - qt-main=5.15.15=hbe73643_5
  - qt6-main=6.9.2=h6c90349_1
  - readline=8.3=hb682ff5_0
  - scikit-learn=1.3.2=py310hc266c7b_2
  - scipy=1.11.4=py310he45c16d_0
  - sip=6.15.0=py310hbe5e9e6_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.1.10=h8d0c38d_1
  - svt-av1=1.7.0=h2f0025b_0
  - tbb=2022.3.0=h0eac15c_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h0dc03b3_103
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py310he491f25_0
  - unicodedata2=17.0.0=py310h5b55623_1
  - wayland=1.24.0=h698ed42_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - x264=1!164.3095=h4e544f5_2
  - x265=3.5=hdd96247_3
  - xcb-util=0.4.1=hca56bd8_2
  - xcb-util-cursor=0.1.6=he30d5cf_0
  - xcb-util-image=0.4.0=h5c728e9_2
  - xcb-util-keysyms=0.4.1=h5c728e9_0
  - xcb-util-renderutil=0.3.10=h5c728e9_0
  - xcb-util-wm=0.4.2=h5c728e9_0
  - xkeyboard-config=2.46=he30d5cf_0
  - xorg-libice=1.1.2=h86ecc28_0
  - xorg-libsm=1.2.6=h0808dbd_0
  - xorg-libx11=1.8.12=hca56bd8_0
  - xorg-libxau=1.0.12=he30d5cf_1
  - xorg-libxcomposite=0.4.6=h86ecc28_2
  - xorg-libxcursor=1.2.3=h86ecc28_0
  - xorg-libxdamage=1.1.6=h86ecc28_0
  - xorg-libxdmcp=1.1.5=he30d5cf_1
  - xorg-libxext=1.3.7=he30d5cf_0
  - xorg-libxfixes=6.0.2=he30d5cf_0
  - xorg-libxi=1.8.2=h57736b2_0
  - xorg-libxrandr=1.5.5=he30d5cf_0
  - xorg-libxrender=0.9.12=h86ecc28_0
  - xorg-libxshmfence=1.3.3=h86ecc28_0
  - xorg-libxtst=1.2.5=h57736b2_3
  - xorg-libxxf86vm=1.1.7=he30d5cf_0
  - yaml=0.2.5=h80f16a2_3
  - zlib=1.3.1=h86ecc28_2
  - zlib-ng=2.3.2=ha7cb516_1
  - zstd=1.5.7=h85ac4a6_6
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - anyio==4.12.1
      - argcomplete==3.6.3
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - catkin-pkg==1.1.0
      - cffi==2.0.0
      - click==8.3.1
      - colcon-argcomplete==0.3.3
      - colcon-bash==0.5.0
      - colcon-cd==0.1.1
      - colcon-cmake==0.2.29
      - colcon-common-extensions==0.3.0
      - colcon-core==0.20.1
      - colcon-defaults==0.2.9
      - colcon-devtools==0.3.0
      - colcon-library-path==0.2.1
      - colcon-metadata==0.2.5
      - colcon-notification==0.3.0
      - colcon-output==0.2.13
      - colcon-package-information==0.4.0
      - colcon-package-selection==0.2.10
      - colcon-parallel-executor==0.4.0
      - colcon-pkg-config==0.1.0
      - colcon-powershell==0.4.0
      - colcon-python-setup-py==0.2.9
      - colcon-recursive-crawl==0.2.3
      - colcon-ros==0.5.0
      - colcon-test-result==0.3.8
      - colcon-zsh==0.5.0
      - coverage==7.13.2
      - crcmod==1.7
      - cryptography==46.0.3
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distlib==0.4.0
      - docutils==0.22.4
      - empy==3.3.4
      - fastjsonschema==2.21.2
      - filelock==3.20.3
      - flatbuffers==25.12.19
      - fqdn==1.5.1
      - fsspec==2026.1.0
      - grpcio==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - iniconfig==2.3.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.6
      - jmespath==0.10.0
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - lz4==4.4.5
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mediapipe==0.10.14
      - mistune==3.2.0
      - ml-dtypes==0.5.4
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - notebook==7.5.3
      - notebook-shim==0.2.4
      - notify2==0.3.1
      - numpy==2.2.6
      - onnx==1.20.1
      - onnx-ir==0.1.15
      - onnxscript==0.5.7
      - opencv-contrib-python==4.13.0.90
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - opt-einsum==3.4.0
      - ordered-set==4.1.0
      - oss2==2.17.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pexpect==4.9.0
      - pluggy==1.6.0
      - prometheus-client==0.24.1
      - protobuf==4.25.8
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pycparser==3.0
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - pytest-repeat==0.9.4
      - pytest-rerunfailures==16.1
      - python-json-logger==4.0.0
      - pytz==2023.4
      - referencing==0.37.0
      - requests==2.28.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==13.4.2
      - rosbags==0.11.0
      - rpds-py==0.30.0
      - ruamel-yaml==0.19.1
      - send2trash==2.1.0
      - setuptools==60.2.0
      - smbus2==0.6.0
      - sounddevice==0.5.5
      - soupsieve==2.8.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.3.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.65.2
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - ultralytics==8.4.6
      - uri-template==1.3.0
      - urllib3==1.26.20
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - yapf==0.43.0
      - zstandard==0.25.0
prefix: /home/boxbunny/miniconda3/envs/boxing_ai
