name: boxing_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.3=he30d5cf_0
  - backports.zstd=1.3.0=py310hfa1aa29_0
  - brotli=1.2.0=hd651790_1
  - brotli-bin=1.2.0=he30d5cf_1
  - brotli-python=1.2.0=py310hbe54bbb_1
  - bzip2=1.0.8=h4777abc_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h0b6afd8_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - chumpy=0.70=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hf54e67a_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=h6c5dea3_0
  - cython=3.2.4=py310h0d97cfb_0
  - dbus=1.16.2=h70963c4_1
  - double-conversion=3.4.0=hfae3067_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h8dda3cd_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310h2d8da20_0
  - freetype=2.14.1=h8af1aa0_0
  - graphite2=1.3.14=hfae3067_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.2=h1134a53_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=hb1525cb_0
  - idna=3.11=pyhd8ed1ab_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - keyutils=1.6.3=h86ecc28_0
  - kiwisolver=1.4.9=py310h65c7496_2
  - krb5=1.21.3=h50a48e9_0
  - lcms2=2.18=h9d5b58d_0
  - ld_impl_linux-aarch64=2.45=default_h1979696_105
  - lerc=4.0.0=hfdc4d58_1
  - libblas=3.11.0=5_haddc8a3_openblas
  - libbrotlicommon=1.2.0=he30d5cf_1
  - libbrotlidec=1.2.0=he30d5cf_1
  - libbrotlienc=1.2.0=he30d5cf_1
  - libcblas=3.11.0=5_hd72aa62_openblas
  - libclang-cpp21.1=21.1.8=default_he95a3c9_2
  - libclang13=21.1.8=default_h94a09a5_2
  - libcups=2.3.3=h5cdc715_5
  - libdeflate=1.25=h1af38f5_0
  - libdrm=2.4.125=he30d5cf_1
  - libedit=3.1.20250104=pl5321h976ea20_0
  - libegl=1.7.0=hd24410f_2
  - libexpat=2.7.3=hfae3067_0
  - libffi=3.5.2=h376a255_0
  - libfreetype=2.14.1=h8af1aa0_0
  - libfreetype6=2.14.1=hdae7a39_0
  - libgcc=15.2.0=h8acb6b2_16
  - libgcc-ng=15.2.0=he9431aa_16
  - libgfortran=15.2.0=he9431aa_16
  - libgfortran5=15.2.0=h1b7bec0_16
  - libgl=1.7.0=hd24410f_2
  - libglib=2.86.3=hf53f6bf_0
  - libglvnd=1.7.0=hd24410f_2
  - libglx=1.7.0=hd24410f_2
  - libgomp=15.2.0=h8acb6b2_16
  - libiconv=1.18=h90929bb_2
  - libjpeg-turbo=3.1.2=he30d5cf_0
  - liblapack=3.11.0=5_h88aeb00_openblas
  - libllvm21=21.1.8=hfd2ba90_0
  - liblzma=5.8.2=he30d5cf_0
  - libnsl=2.0.1=h86ecc28_1
  - libntlm=1.4=hf897c2e_1002
  - libopenblas=0.3.30=pthreads_h9d3fd7e_4
  - libopengl=1.7.0=hd24410f_2
  - libpciaccess=0.18=h86ecc28_0
  - libpng=1.6.54=h1abf092_0
  - libpq=18.1=hf8816c8_3
  - libsqlite=3.51.2=h10b116e_0
  - libstdcxx=15.2.0=hef695bb_16
  - libstdcxx-ng=15.2.0=hdbbeba8_16
  - libtiff=4.7.1=hdb009f0_1
  - libuuid=2.41.3=h1022ec0_0
  - libvulkan-loader=1.4.328.1=h8b8848b_0
  - libwebp-base=1.6.0=ha2e29f5_0
  - libxcb=1.17.0=h262b8f6_0
  - libxcrypt=4.4.36=h31becfc_1
  - libxkbcommon=1.13.1=h3c6a4c8_0
  - libxml2=2.15.1=h825857f_1
  - libxml2-16=2.15.1=h79dcc73_1
  - libxslt=1.1.43=h6700d25_1
  - libzlib=1.3.1=h86ecc28_2
  - matplotlib=3.10.8=py310hbbe02a8_0
  - matplotlib-base=3.10.8=py310hc06f52e_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=ha32ae93_3
  - openjpeg=2.5.4=h5da879a_0
  - openldap=2.6.10=h30c48ee_0
  - openssl=3.6.1=h546c87b_1
  - packaging=26.0=pyhcf101f3_0
  - pcre2=10.47=hf841c20_0
  - pillow=12.1.0=py310hd8fe58f_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h7ac5ae9_1
  - pthread-stubs=0.4=h86ecc28_1002
  - pycocotools=2.0.11=py310h3fe14e7_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h28be5d3_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyyaml=6.0.3=py310h2d8da20_0
  - qhull=2020.2=h70be974_5
  - qt6-main=6.10.1=h5343e53_4
  - readline=8.3=hb682ff5_0
  - requests=2.32.5=pyhcf101f3_1
  - scikit-learn=1.7.2=py310h038361a_0
  - scipy=1.15.2=py310hf37559f_0
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h0dc03b3_103
  - tornado=6.5.4=py310he491f25_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - unicodedata2=17.0.0=py310h5b55623_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wayland=1.24.0=h4f8a99f_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - xcb-util=0.4.1=hca56bd8_2
  - xcb-util-cursor=0.1.6=he30d5cf_0
  - xcb-util-image=0.4.0=h5c728e9_2
  - xcb-util-keysyms=0.4.1=h5c728e9_0
  - xcb-util-renderutil=0.3.10=h5c728e9_0
  - xcb-util-wm=0.4.2=h5c728e9_0
  - xkeyboard-config=2.46=he30d5cf_0
  - xorg-libice=1.1.2=h86ecc28_0
  - xorg-libsm=1.2.6=h0808dbd_0
  - xorg-libx11=1.8.12=hca56bd8_0
  - xorg-libxau=1.0.12=he30d5cf_1
  - xorg-libxcomposite=0.4.6=h86ecc28_2
  - xorg-libxcursor=1.2.3=h86ecc28_0
  - xorg-libxdamage=1.1.6=h86ecc28_0
  - xorg-libxdmcp=1.1.5=he30d5cf_1
  - xorg-libxext=1.3.7=he30d5cf_0
  - xorg-libxfixes=6.0.2=he30d5cf_0
  - xorg-libxi=1.8.2=h57736b2_0
  - xorg-libxrandr=1.5.5=he30d5cf_0
  - xorg-libxrender=0.9.12=h86ecc28_0
  - xorg-libxtst=1.2.5=h57736b2_3
  - xorg-libxxf86vm=1.1.7=he30d5cf_0
  - yaml=0.2.5=h80f16a2_3
  - zlib-ng=2.3.2=ha7cb516_1
  - zstd=1.5.7=h85ac4a6_6
  - pip:
      - absl-py==2.4.0
      - addict==2.4.0
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - catkin-pkg==1.1.0
      - cffi==2.0.0
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docutils==0.22.4
      - empy==3.3.4
      - fastjsonschema==2.21.2
      - filelock==3.20.3
      - flatbuffers==25.12.19
      - fqdn==1.5.1
      - fsspec==2026.1.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.6
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - lz4==4.4.5
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mediapipe==0.10.14
      - mistune==3.2.0
      - ml-dtypes==0.5.4
      - mmengine==0.10.7
      - mpmath==1.3.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - notebook==7.5.3
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - onnx==1.20.1
      - opencv-contrib-python==4.13.0.90
      - opencv-python==4.13.0.90
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pexpect==4.9.0
      - prometheus-client==0.24.1
      - protobuf==4.25.8
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pycparser==3.0
      - pygments==2.19.2
      - pyrealsense2==2.56.5.9235
      - pyside6==6.8.0.2
      - pyside6-addons==6.8.0.2
      - pyside6-essentials==6.8.0.2
      - python-json-logger==4.0.0
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.3.1
      - rosbags==0.11.0
      - rpds-py==0.30.0
      - ruamel-yaml==0.19.1
      - send2trash==2.1.0
      - shiboken6==6.8.0.2
      - smbus2==0.6.0
      - sounddevice==0.5.5
      - soupsieve==2.8.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.3.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.3.0
      - torchaudio==2.3.0+952ea74
      - torchvision==0.18.0a0+6043bc2
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - ultralytics==8.4.6
      - uri-template==1.3.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - yapf==0.43.0
      - zstandard==0.25.0
prefix: /home/boxbunny/miniconda3/envs/boxing_ai
