/**:
  ros__parameters:
    enable_color: true
    enable_depth: true
    align_depth.enable: true
    depth_module.profile: "640x480x30"
    rgb_camera.profile: "640x480x30"
    pointcloud.enable: false
    serial_no: "216322072730"
